defaults:
  - _self_
  - augmentation: pet_augs_od
  - callbacks: callbacks
  - datamodule: digits_od
  - inference: basic
  - logging: wandb
  - loss: yolo_loss
  - metric: map
  - model: pet_model_od
  - optimizer: adamw
  - private: default
  - scheduler: plateau
  - trainer: default_trainer
  - training: default_training
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

general:
  logs_folder_name: logs
  workspace: erlemar
  project_name: pet_project_object_detection
  device: cuda
  log_code: True
  save_pytorch_model: True
  save_best: True
  convert_to_jit: False
  predict: True

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.num}_${datamodule.fold_n}
