path: /Users/andreylukyanenko/Documents/Projects/ds/Data Science/projects/digit-draw-detect_prepare/dataset
n_folds: 5
fold_n: 0
class_name: src.datasets.digit_dataset.DigitDataset
data_module_name: src.lightning_classes.datamodule_digits.DigitsDataModule
labels_to_ohe: False
num_workers: 8
batch_size: 54
multiprocessing_context: fork
pin_memory: True
main_image_size: 32
collate_fn:
mix_params:
  alpha: 0.4
train_len: 1
