path: /Users/andreylukyanenko/Documents/Projects/ds/Data Science/projects/digit-draw-detect_prepare/dataset
n_folds: 5
fold_n: 0
class_name: src.datasets.digit_dataset_yolo.DigitYOLODataset
data_module_name: src.lightning_classes.datamodule_digits_yolo.DigitsYoloDataModule
labels_to_ohe: False
num_workers: 0
batch_size: 64
multiprocessing_context:
pin_memory: True
#main_image_size: 64
main_image_size: 192
collate_fn:
mix_params:
  alpha: 0.4
train_len: 1
